# Generated by Django 3.0.3 on 2020-04-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=400)),
                ('tweet', models.TextField(verbose_name='tweet')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='ItemsToScrape',
        ),
    ]
