# Generated by Django 3.0.3 on 2020-04-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200416_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetapi',
            name='tweet_id',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
