# Generated by Django 3.0.3 on 2020-04-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tweetapi_tweet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweetapi',
            old_name='tweet',
            new_name='tweet_content',
        ),
        migrations.RenameField(
            model_name='tweetapi',
            old_name='date',
            new_name='tweet_date',
        ),
        migrations.RenameField(
            model_name='tweetapi',
            old_name='handle',
            new_name='tweet_handle',
        ),
        migrations.RenameField(
            model_name='tweetapi',
            old_name='url',
            new_name='tweet_url',
        ),
    ]
